baseURL = "http://example.org/"
languageCode = "en-us"
title = "CoVid-19 Tech"
theme = "loveit"

[params]
  # LoveIt theme version
  version = "0.2.X"

[params.footer]
	hugo = false

[menu]
  
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact/"
    title = ""
    weight = 3
