baseURL = "http://example.org/"
languageCode = "en-us"
title = "COVID-19 Tech"
theme = "loveit"

[params]
  # LoveIt theme version
  version = "0.2.X"

[params.footer]
	hugo = false

[menu]
  
  [[menu.main]]
    identifier = "apps"
    pre = ""
    post = ""
    name = "Contact Tracing Apps"
    url = "/apps/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 3
  [[menu.main]]
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact/"
    title = ""
    weight = 3

[params.list]
    # special amount of posts in each list page
    paginate = 50
    
[params.section]
    # special amount of posts in each section page
    paginate = 50

      


