baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cov19Tech"
theme = "loveit"

[params]
  # LoveIt theme version
  version = "0.2.X"

[params.footer]
	hugo = false
    copyright = false
    license = '<p xmlns:dct="http://purl.org/dc/terms/" xmlns:cc="http://creativecommons.org/ns#" class="license-text">This work  CC BY 4.0<a href="https://creativecommons.org/licenses/by/4.0"><img style="height:22px!important;margin-left: 3px;vertical-align:text-bottom;" src="https://search.creativecommons.org/static/img/cc_icon.svg" /><img  style="height:22px!important;margin-left: 3px;vertical-align:text-bottom;" src="https://search.creativecommons.org/static/img/cc-by_icon.svg" /></a></p>'
    

[menu]
  
  [[menu.main]]
    identifier = "apps"
    pre = ""
    post = ""
    name = "Contact Tracing Apps"
    url = "/apps/"
    title = ""
    weight = 2
  
[[menu.main]]
    identifier = "help"
    pre = ""
    post = ""
    name = "Help Out"
    url = "/helpout/"
    title = ""
    weight = 3
[[menu.main]]
    identifier = "contact"
    pre = ""
    post = ""
    name = "Contact"
    url = "/contact/"
    title = ""
    weight = 4
[[menu.main]]
    identifier = "about"
    pre = ""
    post = ""
    name = "About"
    url = "/about/"
    title = ""
    weight = 5

  

[params.list]
    # special amount of posts in each list page
    paginate = 50
    
[params.section]
    # special amount of posts in each section page
    paginate = 50

      


